2025-03-07 11:53:26,281 - 2524842747
[ERROR] <module>:
 3 - Какое то действие в базе данных
2025-03-07 11:53:26,281 - 2524842747
[ERROR] <module>:
 3 - Какое то действие в базе данных
2025-03-07 11:53:26,281 - 2524842747
[ERROR] <module>:
 3 - Какое то действие в базе данных
2025-03-07 12:05:30,168 - 1236628758
[WARNING] <module>:
 3 - Предупреждение из программы
2025-03-07 12:05:30,217 - 1236628758
[ERROR] <module>:
 4 - Ошибка
2025-03-07 12:07:14,989 - 1236628758
[WARNING] <module>:
 3 - Предупреждение из программы
2025-03-07 12:07:14,990 - 1236628758
[ERROR] <module>:
 4 - Ошибка
2025-03-07 12:07:30,458 - 1236628758
[WARNING] <module>:
 3 - РџСЂРµРґСѓРїСЂРµР¶РґРµРЅРёРµ РёР· РїСЂРѕРіСЂР°РјРјС‹
2025-03-07 12:07:30,508 - 1236628758
[ERROR] <module>:
 4 - РћС€РёР±РєР°
2025-03-07 12:42:51,721 - 959086433
[ERROR] <module>:
 7 - Traceback (most recent call last):
  File "C:\Users\NatalkaNerealka\AppData\Local\Temp\ipykernel_13468\959086433.py", line 5, in <module>
    10 / 0
    ~~~^~~
ZeroDivisionError: division by zero

